version: "2"
services:
  lochat:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: "production"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "lochat"
      DB_PASSWORD: 85858585
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./logs:/usr/src/lochatbackend/logs
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "lochat"
      POSTGRES_PASSWORD: 85858585