version: "2"
services:
  lochat:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: "production"
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - postgres
  postgres:
    build:
      context: ./database
    restart: always
    environment:
      POSTGRES_USER: "lochat"
      POSTGRES_PASSWORD: 85858585