version: "3"
services:
  databus:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: "production"
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "lochat"
      POSTGRES_PASSWORD: 85858585